include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Notification26Prefs
Notification26Prefs_INSTALL_PATH = /Library/PreferenceBundles
Notification26Prefs_FRAMEWORKS = UIKit
Notification26Prefs_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
